---
- name: Write env config
  notify:
    - Restart errors
  ansible.builtin.template:
    src: default.j2
    dest: /etc/default/errors
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - errors

- name: Write service file
  notify:
    - Restart errors
  ansible.builtin.template:
    src: service.j2
    dest: /etc/systemd/system/errors.service
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - errors

- name: Pull docker image
  when:
    - errors_pull_image
  community.docker.docker_image:
    name: "{{ errors_image }}"
    source: pull
  tags:
    - errors

- name: Create docker network
  when:
    - errors_network | default(False)
  community.docker.docker_network:
    name: '{{ errors_network }}'
  tags:
    - errors

- name: Start errors service
  ansible.builtin.systemd:
    name: errors
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - errors

...
