# Standards: 1.2
---
- name: Write env config
  notify:
    - Restart errors
  template:
    src: default.j2
    dest: /etc/default/errors
  tags:
    - errors

- name: Write service file
  notify:
    - Restart errors
  template:
    src: service.j2
    dest: /etc/systemd/system/errors.service
  tags:
    - errors

- name: Create docker network
  when: errors_network | default(False)
  docker_network:
    name: '{{ errors_network }}'

- name: Start errors service
  systemd:
    name: errors
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - errors

...
